//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtamataTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OtamataTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;Anchorman - The Legend of Ron Burgundy sound clips - Movie Sound Clips&lt;/title&gt;
        ///&lt;meta name=&quot;description&quot; content=&quot;Sound clips (wav, mp3, ogg, flac) from the movie Anchorman - The Legend of Ron Burgundy&quot;&gt;
        ///&lt;meta name=&quot;keywords&quot; content=&quot;anchorman - the legend of ron burgundy wavs, anchorman - the legend of ron burgundy wav, anchorman - the legend of ron burgundy sound clips, anchorman - the legend of ron burgundy sounds, anchorman wavs, anchorman sound clips, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string anchorman_yahoo_result_1 {
            get {
                return ResourceManager.GetString("anchorman_yahoo_result_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html  xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///
        ///
        ///
        ///&lt;title&gt;The MovieWavs Page - Anchorman The Legend Of Ron Burgundy Wavs Mp3s Movie Quotes Movie Sounds Movie Wavs&lt;/title&gt;
        ///&lt;link rel=&quot;shortcut icon&quot; href=&quot;/favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///&lt;link rel=&quot;alternate&quot; type=&quot;application/rss+xml&quot; title=&quot;MovieWavs.com Updates&quot; href=&quot;/rss/index.xml&quot;/&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string anchorman_yahoo_result_2 {
            get {
                return ResourceManager.GetString("anchorman_yahoo_result_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;Movies and Television Wav Central: 
        ///Anchorman 
        ///Audio Sound Files Clips Database&lt;/title&gt;
        ///&lt;META NAME=&quot;Description&quot; CONTENT=&quot;A searchable database of 
        ///Anchorman 
        ///audio files and sound clip files (mp3 and wav).  Sounds are categorized by type, including movies, tv, effects.&quot;&gt;
        ///&lt;META NAME=&quot;KeyWords&quot; CONTENT=&quot;
        ///Anchorman
        ///,mp3,wav,files,wavs,sounds,comedy,funny,movie,movies,television,tv,audio,sound,play,clips,mpeg,au,real,multimedia,media,video,videos,South Park,Star Wars&quot;&gt;
        ///&lt;style&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string anchorman_yahoo_result_3 {
            get {
                return ResourceManager.GetString("anchorman_yahoo_result_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot; &quot;http://www.w3.org/TR/html4/loose.dtd&quot;&gt;
        ///&lt;html xmlns:og=&quot;http://opengraphprotocol.org/schema/&quot;
        ///      xmlns:fb=&quot;http://www.facebook.com/2008/fbml&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=iso-8859-1&quot;&gt;
        ///&lt;script type=&quot;text/javascript&quot;&gt;var IMDbTimer={starttime: new Date().getTime()};&lt;/script&gt;
        ///&lt;script&gt;
        ///var addClickstreamHeadersToAjax = function(xhr) {
        ///    xhr.setRequestHeader(&quot;x-imdb-parent-id&quot;, &quot;1Q64Z71H6X7HXF4GHQY [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string anchorman_yahoo_result_4 {
            get {
                return ResourceManager.GetString("anchorman_yahoo_result_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;Free Anchorman Sounds, Sound Clips, Sound Bites, and Sound Effects&lt;/title&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///        &lt;meta name=&quot;keywords&quot; content=&quot;Anchorman Sounds, Anchorman Sound Clips, Anchorman Sound Effects, Anchorman Sound Bites, Anchorman Quotes,&quot;/&gt;    
        ///        &lt;meta name=&quot;descript [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string anchorman_yahoo_result_5 {
            get {
                return ResourceManager.GetString("anchorman_yahoo_result_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html  xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///
        ///
        ///
        ///&lt;title&gt;The MovieWavs Page - Wavs Mp3s Movie Quotes Movie Sounds Movie Wavs&lt;/title&gt;
        ///&lt;link rel=&quot;shortcut icon&quot; href=&quot;/favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///&lt;link rel=&quot;alternate&quot; type=&quot;application/rss+xml&quot; title=&quot;MovieWavs.com Updates&quot; href=&quot;/rss/index.xml&quot;/&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=ISO-8859-1&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string anchorman_yahoo_result_6 {
            get {
                return ResourceManager.GetString("anchorman_yahoo_result_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;Free Anchorman The Legend Of Ron Burgundy Sounds, Sound Clips, Sound Bites, and Sound Effects&lt;/title&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///        &lt;meta name=&quot;keywords&quot; content=&quot;Anchorman The Legend Of Ron Burgundy Sounds, Anchorman The Legend Of Ron Burgundy Sound Clips, Anchorman The Legend  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string anchorman_yahoo_result_7 {
            get {
                return ResourceManager.GetString("anchorman_yahoo_result_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xml:lang=&quot;en&quot; lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;Young Frankenstein Sounds Movie Wav or MP3&lt;/title&gt;
        ///&lt;meta name=&quot;Description&quot; content=&quot;Preview and download Young Frankenstein sound clips from Movie-Sounds.net. All sounds from the movie Young Frankenstein are available in both .WAV and .MP3 formats.&quot; /&gt;
        ///&lt;meta name=&quot;Keywords&quot; content=&quot;Young Frankenstein,Movie Sound [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string young_frankenstein_result_7 {
            get {
                return ResourceManager.GetString("young_frankenstein_result_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xml:lang=&quot;en&quot; lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;Young Frankenstein Sounds Movie Wav or MP3&lt;/title&gt;
        ///&lt;meta name=&quot;Description&quot; content=&quot;Preview and download Young Frankenstein sound clips from Movie-Sounds.net. All sounds from the movie Young Frankenstein are available in both .WAV and .MP3 formats.&quot; /&gt;
        ///&lt;meta name=&quot;Keywords&quot; content=&quot;Young Frankenstein,Movie Sound [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string young_frankenstein_result_8 {
            get {
                return ResourceManager.GetString("young_frankenstein_result_8", resourceCulture);
            }
        }
    }
}
