using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using OttaMatta.Common;

namespace OttaMatta.Common
{
    public class LogFile
    {
        private static string _logFileSync = "logFileSync";

        private string _logFileName = string.Empty;
        private string _logFilePath = string.Empty;
        private bool _useDateInFName = true;
        private bool _formatWithTime = true;

        /// <summary>
        /// Logfile name, autogenerated as it's requested.
        /// </summary>
        public string LogFileName
        {
            get 
            {
                string exeFilename = Functions.IsEmptyString(_logFileName) ? "myapplication" : _logFileName;

                return string.Format("{0}-log{1}.txt", exeFilename, _useDateInFName ? string.Format("-{0:yyyy-MM-dd}", DateTime.Now) : "");
            }
            set 
            { 
                _logFileName = value; 
            }
        }

        public string LogFilePath
        {
            get { return _logFilePath; }
            set { _logFilePath = value; }
        }

        /// <summary>
        /// Defaults to true.
        /// </summary>
        public bool UseDateInFName
        {
            get { return _useDateInFName; }
            set { _useDateInFName = value; }
        }

        /// <summary>
        /// Set to false to turn off formatting each message that's logged with the time prepended.  By default it's on.
        /// </summary>
        public bool FormatWithTime
        {
            get { return _formatWithTime; }
            set { _formatWithTime = value; }
        }

        public static string FormatMsgWithTime(string msg)
        {
            return string.Format("{0}  {1}\r\n", DateTime.Now, msg);
        }

        /* Doesn't seem to be working in Win7 - do some googleing
        public void SetLogfilePathToDesktop()
        {
            _logFilePath = Environment.GetFolderPath(Environment.SpecialFolder.DesktopDirectory);
        }
        */
        /// <summary>
        /// Constructor.
        /// </summary>
        public LogFile()
        {
            // todo: set file to name of exe plus .txt
            _logFilePath = string.Empty;
        }

        public void Log(string message)
        {
            string fileName = Functions.BuildFilenameFromElements(_logFilePath, LogFileName);

            if (_formatWithTime)
            {
                message = FormatMsgWithTime(message);
            }

            lock (_logFileSync)
            {
                Functions.WriteStringAsFile(message, fileName, true);
            }
        }
    }
}
